### PR TITLE
 Update Dockerfile dependencies for local development and CI

### PR DESCRIPTION
**Pull request by aaron-contreras**
## Issues:
- Dockerfile `chromium` and `nss` versions were no longer supported.
- Missing `gcompat` library for running on a Silicon chip.
- No coverage against Ruby 3.1 and Ruby 3.2
- Ruby 2.6 is EOL
- Dependencies need update for support (rspec-rails, bundler)

### Changes

- [x] Add latest working chromium and nss versions to Dockerfile.dev and Dockerfile.test
- [x] Add gcompat library needed for Apple Silicon development
- [x] Commit updated `Gemfile.lock` and `package-lock.json` for dummy
- [x] Add coverage against Ruby `3.1` and `3.2`
- [x] Deprecate coverage against Ruby `2.6`
- [x] Update `bundler` version
- [x] Update `rspec-rails` version

### Notes

Ruby `>= 3.1` uses `Psych 4.x` and this causes YAML load problems.

[Patch by the Rails core team here](https://github.com/rails/rails/commit/1e56b1d1152e8ab74203db30625116844614cc78). Because of this, I set the Rails version to `~> 7.0.4` on the `Gemfile.7.0`.

In order to test Ruby 3.1 and Ruby 3.2 against Rails 6, the `psych` gem needs to be locked to `< 4`.

### CODE REVIEW

**Review by jonasjabari — APPROVED** [review]

**Comment by jonasjabari** [comment]
@aaron-contreras do you know wh the ruby 2.6 ci containers faill?

**Comment by aaron-contreras** [comment]
> @aaron-contreras do you know wh the ruby 2.6 ci containers faill?

@jonasjabari I can pick up from the failures that there's a clash between the puma and capybara versions used in those Gemfiles. But since they're unversioned and there's no lock file for it, I'm unsure as to how to solve this.

**Comment by jonasjabari** [comment]
2.6 is EOL https://endoflife.date/ruby
We should simply remove these test containers and add ones for newer ruby versions 3.1 and 3.2 instead? @aaron-contreras what is your opinion?

**Comment by aaron-contreras** [comment]
> 2.6 is EOL https://endoflife.date/ruby
> We should simply remove these test containers and add ones for newer ruby versions 3.1 and 3.2 instead? @aaron-contreras what is your opinion?

@jonasjabari Agreed. I'll also track down sections throughout the documentation where we reference which Ruby/Rails versions the gem is tested against and update accordingly.

**Comment by aaron-contreras** [comment]
@jonasjabari Coverage for Ruby 3.1 and 3.2 added. Some Gemfile dependencies updated as well as upgraded the ruby versions for local development. The docs portion listing the Ruby/Rails versions the gem is tested against has been updated as well.

**Pull request merged**
